### PR TITLE
compat: build against both pinned DuckDB v1.5 and DuckDB main (v2.0)

### PR DESCRIPTION
**Pull request by teaguesterling**
## Why

`duckdb/community-extensions` builds **every release PR** against `v2.0-cyanoptera`. Its `build_next.yml` triggers on exactly a `description.yml` change — which is what a release PR *is* — and there is **no per-extension opt-out**:

```yaml
on:
  pull_request:
    paths-ignore: ['**', '!extensions/*/description.yml']
jobs:
  test_against_latest:
    with:
      duckdb_version: 'v2.0-cyanoptera'
```

So an extension that does not compile against DuckDB main shows a red check on every single release. This PR makes duck_tails **source-compatible** with both lines.

**This is not a migration.** duck_tails keeps shipping against the pinned `v1.5.4` submodule, and nothing about the shipped build changes. The whole Identifier change class is a literal no-op there (`CompatName` *is* `string` on the pin), and the full suite stayed green through every rebuild: `All tests passed (920 assertions in 55 test cases)`.

## Approach: ask DuckDB what it does, don't guess from version numbers

Every shim in `src/include/duckdb_compat.hpp` detects a **capability**, never a version, and each API change is detected **separately** — tying several to one macro silently picks the wrong branch the moment they land in different releases.

Two of the fixes below are cases where the obvious detection was **wrong in the dangerous direction: it would have broken the version we ship**, not the one we are porting to. That is the theme of this PR more than any individual signature change.

All shims tag-dispatch rather than using `if constexpr`, so the header stays valid at C++11 — some extensions here compile their TUs at C++11 on purpose, because forcing C++17 on the extension but not on libduckdb gives duckdb's static-const header members implicit inline linkage in one and not the other, and the link fails with multiple definitions. **The dispatch targets must be templates**; as plain functions both branches compile and the one naming the absent member fails.

### `CompatName` must be derived from DuckDB, not probed for

`#if __has_include("duckdb/common/identifier.hpp")` looks like the right detection and is a time bomb:

| branch | identifier.hpp | `table_function_bind_t` takes |
|---|---|---|
| `v1.5-variegata` @ our pin | absent | `vector<string>` |
| `v1.5-variegata` @ branch tip | **present** | `vector<string>` |
| `main` (v2.0) | present | `vector<Identifier>` |

`identifier.hpp` was **backported to the stable branch without changing the bind signature**. The header probe is correct today only by the accident that our pin predates the backport — the next routine submodule bump would flip `CompatName` to `Identifier` on a DuckDB that still wants strings, and **all 35 bind signatures in this repo would stop compiling at once**, with nothing about the bump pointing at the compat header.

A header probe answers *"did this header land"*. The question is *"what does the bind callback take"*. So ask DuckDB that directly:

```cpp
using CompatName = typename std::remove_reference<
    decltype(std::declval<TableFunctionBindInput &>().input_table_names)>::type::value_type;
```

`TableFunctionBindInput::input_table_names` has the same element type as the bind out-parameter on both lines (`table_function.hpp:110`/`:289` on the pin, `:123`/`:319` on main), so this cannot drift — if the two disagreed, DuckDB itself would be inconsistent. Verified rather than assumed: a bind function declared with `vector<CompatName> &` is assignable to `table_function_bind_t` on the pin, and `static_assert(is_same<CompatName, string>)` holds there.

### `ToUnifiedFormat`'s obvious probe never fires

v2.0 did **not** remove `ToUnifiedFormat(count, data)` — it kept it as `[[deprecated]]`. So probing for the count-taking overload is true on *both* versions, and the shim would always take the deprecated path while compiling perfectly clean. The probe asks for the count-**free** overload, which is the one that only exists on v2.0. 5 call sites were affected.

## The rest

**1. `vector<string>` → `vector<Identifier>` in bind signatures — 35 sites, 11 files.** The conversion asymmetry makes this cheap: `Identifier(const char *)` is implicit (literals are identifiers by intent) while `Identifier(const string &)` is explicit. So every `names = {"repo_path", "file_path", ...}` initialiser compiles unchanged on both versions — **only the signatures move**. No runtime string crosses into or out of a names vector anywhere in duck_tails, so no boundary conversion was needed. Three internal `DefineXxxSchema`/`GetXxxColumnNames` helper chains move with their vectors.

Deliberately **not** touched: `vector<string>` parameters that are genuinely strings (`TextDiff::ComputeDiff` lines, `GitParentsFunctionData::commits`, `LoadFileLines`, `GitFileSystem::transfers`), and `named_parameters` loops — `named_parameter_map_t` is now `identifier_map_t<Value>`, but `Identifier` has `operator==` against `const char *`, so `kv.first == "repo_path"` needs no change.

**2. `FlatVector::GetData<T>` is read-only on v2.0.** 5 result-vector write sites now use `CompatFlatDataMutable`; read sites keep `GetData`. `ConstantVector` did *not* gain a `GetDataMutable` — it kept a const-overloaded pair, so its sites need nothing, and the shim lands on the right branch for both.

**3. `FlatVector::Validity` got the same const-split — and this one is grep-resistant.** Unlike the `GetData` split, **the accessor call still compiles on v2.0**: `auto &m = FlatVector::Validity(v)` just deduces a const reference. The failure surfaces later, at the mutation:

```
src/text_diff.cpp:183: error: passing 'const duckdb::ValidityMask' as 'this'
argument discards qualifiers [-fpermissive]
```

Neither `Validity` nor `FlatVector` appears in that message, so grepping for the accessor finds nothing — you have to grep for `SetInvalid`/`SetValid` and walk back to where the reference was bound. The canary found this one.

**4. Output cardinality is now probed on the member, not on a header** (`__has_include("…/vector/list_vector.hpp")` → probe for `DataChunk::SetChildCardinality`) — same class of latent break as `CompatName`, and it would likewise have hit the pinned build.

All 25 call sites were audited for **order**, since forwarding `SetCardinality` to `SetChildCardinality` is unsafe for callers that mutate child vectors first. That warning does not apply here, and the reasoning is recorded in the header so nobody "fixes" it later: every site is *write-at-index*-then-set, writing at an index does not update a vector's tracked size, so these sites **need** `SetChildCardinality` — `SetCardinalityUnsafe` would leave every child at size 0. Doing it after the writes is safe because `SetChildCardinality` only calls `FlatVector::SetSize`, which bounds-checks and assigns `v_size`; it moves no data. The callers upstream warns about are `Vector::Append`-style ones, which duck_tails has none of.

**5. `SetFallible` deliberately not added.** v2.0 turns a throw from an unmarked scalar function into an `InternalException`. duck_tails has four scalar functions — `text_diff`, `diff_text`, `text_diff_stats`, `git_uri` — and none throws from its execute path (`diff_text` catches `std::exception` and writes an error string). `SetFallible` exists identically on the pin and is optimizer-visible there via `CanThrow()`, so marking defensively would cost the shipped build for nothing.

**6. Canary job un-gated.** `duckdb-next-build` was `if: false`; it is now `if: github.event_name == 'workflow_dispatch'`. It stays off `push`/`pull_request` deliberately: both fire on the same commit and a PR's check rollup includes both, so an ungated canary would show red on every PR while main is ahead of what we ship. It uses `if:` rather than `continue-on-error:` because a job calling a **reusable** workflow accepts only a fixed key set — adding `continue-on-error` makes the whole file fail to parse and schedules *zero* jobs.

Drive it with `gh workflow run MainDistributionPipeline.yml --ref <branch>`. Reading a failure needs the REST API: because the job calls a reusable workflow, `gh run view <run> --log-failed` prints **nothing at all**, which reads exactly like a clean build.

## Verification

- **Pinned v1.5.4, locally:** `All tests passed (920 assertions in 55 test cases)`, re-run after each of the three shim revisions.
- **DuckDB main:** by canary only — the submodule is the stable line, so a local build can only ever prove the v1.5 half. Canary status is reported in the thread below.

## Known-failing, not caused by this PR

The stable v1.5.4 CI job **builds clean on both arches** and then fails 2 of 882 assertions on `linux_amd64` only, green on `linux_arm64`. Both are the same check appearing in two files:

```sql
SELECT COUNT(*) >= 1 FROM git_branches('duckdb') WHERE branch_name = 'main';
```

That asks whether the runner's checkout of the `duckdb` submodule has a local branch named `main` to enumerate — a property of how CI cloned it, not of anything this PR compiles. It passes locally, and it is a wrong result rather than an exception. Tracked separately; a control run against unported `main` is in flight to confirm.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01XoHU19qnngy1CJnXyX1csz

### CODE REVIEW

**Comment by teaguesterling** [comment]
## Verification status

### DuckDB main (v2.0) — **compiles**

Canary run [33838859212](https://github.com/teaguesterling/duck_tails/actions/runs/33838859212) on `a2df29a1`: the v2.0 build is **green**. The log contains nothing from `src/` but deprecation warnings out of duckdb's own `catalog.cpp`.

Across four canary rounds the only compile-level errors ever seen were the three `FlatVector::Validity` mutation sites — everything else compiled first try, which is the signature rename genuinely being the mechanical part.

The job is now red in **tests**, not compilation: 49 passed, 6 failed. See below.

### Pinned v1.5.4 — green

`All tests passed (920 assertions in 55 test cases)`, locally, re-run after each of the three shim revisions. CI builds clean on both arches.

### The amd64-only stable test failure is **pre-existing** — confirmed by A/B, not inferred

I dispatched the same workflow against unported `main` as a control ([33835149474](https://github.com/teaguesterling/duck_tails/actions/runs/33835149474)). It fails **identically**:

| | this branch | unported `main` |
|---|---|---|
| `linux_arm64` | success | success |
| `linux_amd64` | failure | failure |
| failing files | `integration.test:78`, `duck_tails_comprehensive.test:78` | same |
| counts | 882 assertions, 880 passed, 2 failed | same |

Same assertion in both files:

```sql
SELECT COUNT(*) >= 1 AS has_main_branch FROM git_branches('duckdb') WHERE branch_name = 'main';
```

That asks whether the runner's checkout of the `duckdb` submodule has a local branch named `main` to enumerate — a property of how CI cloned it. **Nothing in this PR affects it**, and it passes locally. It needs fixing, but separately — the test is asserting on the CI environment rather than on the extension.

### Outstanding: 6 v2.0 runtime failures

Not caused by compilation and not reproducible locally (the submodule is the stable line, so a local build can only ever prove the v1.5 half). All six go through the `git://` filesystem or a LATERAL `_each` function:

`git_log_path_filter` · `debug_complex_lateral_no_verification` · `duck_tails_comprehensive` · `git_read_each_comprehensive` · `git_tags_each_comprehensive` · `git_tags_comprehensive`

Two things already ruled out:

- **Not the same bug as the stable amd64 failure.** On stable, `duck_tails_comprehensive` fails at line 78; on the canary it fails at line 24 — same file, different test, different cause.
- **Not the v2.0 single-arrow-lambda binder change.** There is not a single `->` character in any of the six files, and no lambda-taking function call anywhere in `src/` or `test/`.

The canary runner's harness prints the failing query and `FAILED` but **not** the actual-vs-expected diff or any exception text, so the log does not say why. A temporary `post_build_command` diagnostic is on the branch to re-run those files serially through the raw unittest binary, which does print it. **That commit is marked TEMP and will be reverted before merge** — the reverted state is already proven green by the canary run above.

These are behaviour differences on a version this extension does not ship. They matter eventually, because community-extensions' `test_against_latest` runs tests and not just the build — but they are a separate workstream from source compatibility, which is what this PR is.
